#Expyriment 0.9.0 (Python 3.6.5), .xpe-file, coding: ISO8859-1
#date: Mon Aug 13 2018 14:30:36
#sha1: None
#modules: 
#display: size=(2732, 768), window_mode=False, open_gl=2
#os: uname_result(system='Linux', node='L3460', release='4.4.0-109-generic', version='#132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
11730,design,log,
#design: #exp: n-back test
#design: block_cnt,block_id,trial_cnt,trial_id
#design: 0,0,0,0
#design: 0,0,1,1
#design: 0,0,2,2
#design: 0,0,3,3
#design: 0,0,4,4
11730,design,logged,
11730,Experiment,started
11731,Stimulus,presented,0
11733,stderr,received,'Traceback (most recent call last):'
11733,stderr,received,'  File "nbacktask.py", line 41, in <module>'
11735,stderr,received,'    exp.clock.wait(1000-trial.stimuli[1].preload())'
11735,stderr,received,'IndexError: list index out of range'
