#Expyriment 0.9.0 (Python 3.6.5), .xpe-file, coding: ISO8859-1
#date: Tue Jul 31 2018 14:54:20
#sha1: None
#modules: 
#display: size=(2732, 768), window_mode=False, open_gl=2
#os: uname_result(system='Linux', node='L3460', release='4.4.0-109-generic', version='#132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
5041,stderr,received,'Traceback (most recent call last):'
5041,stderr,received,'  File "twoblocks.py", line 32, in <module>'
5041,stderr,received,'    block_two = expyriment.design.Block(neme="Block two")'
5041,stderr,received,"TypeError: __init__() got an unexpected keyword argument 'neme'"
